// <auto-generated />
using DataAccessCoreTests;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessCoreTests.Migrations
{
    [DbContext(typeof(TestContext))]
    partial class TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataAccessCoreTests.TestEntities.TestEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ParA");

                    b.Property<string>("ParB");

                    b.Property<int>("TestEntity2ID");

                    b.HasKey("ID");

                    b.HasIndex("TestEntity2ID");

                    b.ToTable("TestEntities");
                });

            modelBuilder.Entity("DataAccessCoreTests.TestEntities.TestEntity2", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ParA");

                    b.HasKey("ID");

                    b.ToTable("TestEntity2s");
                });

            modelBuilder.Entity("DataAccessCoreTests.TestEntities.TestEntity", b =>
                {
                    b.HasOne("DataAccessCoreTests.TestEntities.TestEntity2", "TestEntity2")
                        .WithMany()
                        .HasForeignKey("TestEntity2ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
